apiVersion: v1
entries:
  azure-resource-limits-exporter:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-01-22T10:24:17.9328469+02:00"
    description: Helm Chart for deploying Azure Resource Limits Exporter
    digest: a13b5128a200486e280167d0fd7cdcf61bdad0d9621bb1c19d50223c0eb05eac
    maintainers:
    - email: sovrevage@gmail.com
      name: Stian Øvrevåge
    name: azure-resource-limits-exporter
    sources:
    - https://github.com/equinor/azure-resource-limits-exporter
    urls:
    - azure-resource-limits-exporter-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-01-22T10:24:17.9264268+02:00"
    description: Helm Chart for deploying Azure Resource Limits Exporter
    digest: 39996eb77cfcee8cbfcf74ec38579b1857024311272fe1e21aa393b12fe3de0c
    maintainers:
    - email: sovrevage@gmail.com
      name: Stian Øvrevåge
    name: azure-resource-limits-exporter
    sources:
    - https://github.com/equinor/azure-resource-limits-exporter
    urls:
    - azure-resource-limits-exporter-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-01-22T10:24:17.9204394+02:00"
    description: Helm Chart for deploying Azure Resource Limits Exporter
    digest: d7e68ce453a5ab50f7870f6659e884942755f8ce5c773e7a4d4e22a4598c2b80
    maintainers:
    - email: sovrevage@gmail.com
      name: Stian Øvrevåge
    name: azure-resource-limits-exporter
    sources:
    - https://github.com/equinor/azure-resource-limits-exporter
    urls:
    - azure-resource-limits-exporter-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-01-22T10:24:17.9145439+02:00"
    description: Helm Chart for deploying Azure Resource Limits Exporter
    digest: 4bb6f544e4d3e50a7f7c8551f7efce51f3561856d07851999c7bed65fbbeca77
    maintainers:
    - email: sovrevage@gmail.com
      name: Stian Øvrevåge
    name: azure-resource-limits-exporter
    sources:
    - https://github.com/StianOvrevage/azure-resource-limits-exporter
    urls:
    - azure-resource-limits-exporter-0.1.2.tgz
    version: 0.1.2
generated: "2021-01-22T10:24:17.9082927+02:00"
